server:
  port: 8761

spring:  application:    name: service-discovery

eureka:  client:    register-with-eureka: false
    fetch-registry: false    service-url:
      default: http://localhost:8761      