server:
  port: 8011

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      - id: store-service
        uri: http://store-service
        predicates:        - Path=/store-service/**
